version: "3.9"

services:
  db:
    image: postgres
    logging:
      driver: none
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/short_links_data
    volumes:
      - database:/var/lib/postgresql/short_links_data

  pgadmin4:
    image: dpage/pgadmin4
    logging:
      driver: none
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pg_admin4:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db
    
  web:
    build: app
    restart: always
    command: uvicorn app.main:app --reload --host ${APP_ADDR} --port ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - PATH=/bin:$PATH
    
volumes:
  database:
  pg_admin4:
