"""set link.short_link to unique

Revision ID: ae4c946761fd
Revises: cbb7d7948f6f
Create Date: 2023-01-12 13:14:37.206623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4c946761fd'
down_revision = 'cbb7d7948f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_short_link', table_name='link')
    op.create_index(op.f('ix_link_short_link'), 'link', ['short_link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_short_link'), table_name='link')
    op.create_index('ix_link_short_link', 'link', ['short_link'], unique=False)
    # ### end Alembic commands ###
