"""seq in links

Revision ID: cbb7d7948f6f
Revises: 119b18aa9d59
Create Date: 2023-01-10 21:46:49.140657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb7d7948f6f'
down_revision = '119b18aa9d59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
