"""ini links

Revision ID: d99a9aa8532e
Revises: e562ddb8325a
Create Date: 2023-01-10 15:23:44.142802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99a9aa8532e'
down_revision = 'e562ddb8325a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('long_link', sa.String(), nullable=False),
    sa.Column('short_link', sa.String(), nullable=True),
    sa.Column('redirect_users', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_link_short_link'), 'link', ['short_link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_short_link'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
